title: Carlos Alba
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: yes
footer_url: "https://github.com/calba5141114"
footer_text: "Blog Maintained by Carlos Alba"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "resume.pdf"
 - name: "About"
   link: "/researcher/"
